@startuml
state "Main State" as Main {
  state "Substate A" as A
  state "Substate B" as B
  A --> B: to B
  B --> A: to A
  H:
  H --> A
}
[*] --> Main
Main --> H: Reactivate
Main --> [*] : Finished
@enduml