@startuml
state "Media Player" as MediaPlayer {
  state "Operational" as Operational {
    state "Stopped"
    state "Playing"
    
    Stopped -right-> Playing : Play
    Playing -left-> Stopped : Stop
  }
  ||
  state "Volume" as Volume {
    state "Muted"
    state "Low"
    state "Medium"
    state "High"
    
    Muted --> Low : Unmute
    Low --> Medium : Increase
    Medium --> High : Increase
    High --> Muted : Mute
  }
  ||
  state "Playlist" as Playlist {
    state "Empty"
    state "Loaded"
    
    Empty -down-> Loaded : Load
    Loaded -up-> Empty : Clear
  }
  
  
  Operational : entry / Initialize
  Volume : entry / SetDefaultVolume
  Playlist : entry / LoadPlaylist
}

[*] --> MediaPlayer
@enduml