@startuml

skinparam classAttributeIconSize 0

class Menu {
  menuItems: Set<Meal>
}

class Meal {
  name: String
  price: Double
  ingredients: Set<Ingredient>
}

class Ingredient {
  name: String
  type: String
  expirationDate: Date
  inventoryStatus: InventoryStatus
}

enum InventoryStatus {
  IN_STOCK,
  NEED_TO_ORDER,
  ON_ORDER,
  ON_RECEIVE
}

enum PaymentMethod {
  CARD,
  CASH,
  OTHER
}

enum DeliveryType {
  PICK_UP,
  DELIVERY
}

enum OrderStatus {
  RECEIVED,
  PREPARING,
  WAITING_FOR_PICKUP,
  READY_FOR_PICKUP,
  COMPLETED
}


class User {
  name: String
  DoB: Date
  /age: int
  phone: String
  email: String
  getUserInfo(): String
}

note right of User
  age = currentYear - DoB
end note

class Menu {
  menuItems: <Set>Meal
}


class Cook {
  cookId: int
  specialty: String
}


class Customer {
  customerId: int
  address: String
}

class Order {
  orderId: int
  status: OrderStatus
  paymentMethod: PaymentMethod
  quantity: int
  orderDate: Date
  deliveryType: DeliveryType
}


class Meal {
  mealId: int
}

class Inventory {
  inventoryId: int
  stock: int
}

' customer 继承自 user
User <|-- Customer
' cook 继承自 user
User <|-- Cook
'customer:1 order:0..*
Customer "1" -- "0..*" Order
'cook:1..* order:1
Cook "1..*" -- "1" Order
'ingredient:0..* cook:0..*
Ingredient "0..*" -- "0..*" Cook
Menu "1" -- "1..*" Meal
Meal "0..*" o-- "1..*" Ingredient
'cook "0..*" -- "1" Inventory
Inventory "1" -- "0..*" Cook